/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import computershop.loginForm;
import config.Session;
import javax.swing.JOptionPane;

/**
 *
 * @author Karystel
 */
public class accountDetails extends javax.swing.JFrame {

    /**
     * Creates new form userDashboard
     */
    public accountDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Container = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ut = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        cn = new javax.swing.JTextField();
        un = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        iddisplay = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        acc_email = new javax.swing.JLabel();
        cpas = new javax.swing.JLabel();
        acc_name = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        Container.setBackground(new java.awt.Color(255, 255, 255));
        Container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jLabel10.setText("CONTACT:");
        Container.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 120, 70));

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jLabel9.setText("EMAIL:");
        Container.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 120, 50));

        ut.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "USER" }));
        Container.add(ut, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 290, 50));

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jLabel7.setText("USERNAME:");
        Container.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 120, 30));

        email.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        Container.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 290, 50));

        cn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Container.add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 290, 50));

        un.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        un.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unActionPerformed(evt);
            }
        });
        Container.add(un, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 290, 50));

        jLabel6.setFont(new java.awt.Font("Bookman Old Style", 3, 18)); // NOI18N
        jLabel6.setText("USER TYPE:");
        Container.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 120, 70));

        Header.setBackground(new java.awt.Color(51, 51, 0));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iddisplay.setFont(new java.awt.Font("Bookman Old Style", 3, 30)); // NOI18N
        iddisplay.setForeground(new java.awt.Color(255, 255, 204));
        iddisplay.setText("USER ID:");
        Header.add(iddisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 310, 60));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        jButton1.setText("LOG-OUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Header.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 160, 40));

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 3, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("ACCOUNT DETAILS");
        Header.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 390, -1));

        Container.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 110));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Container.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 109, -1, 390));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cream and Brown Retro Cafe Logo.png"))); // NOI18N
        Container.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 430, 500));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cream and Brown Retro Cafe Logo.png"))); // NOI18N
        Container.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 110, 250, 500));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/pngtree-avatar-icon-profile-icon-member-login-vector-isolated-png-image_1978396-removebg-preview.png"))); // NOI18N
        Container.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 120, 280, 250));

        acc_email.setFont(new java.awt.Font("Bookman Old Style", 3, 16)); // NOI18N
        acc_email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_email.setText("email");
        Container.add(acc_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 260, -1));

        cpas.setFont(new java.awt.Font("Bookman Old Style", 3, 20)); // NOI18N
        cpas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cpas.setText("Change Password");
        cpas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cpasMouseClicked(evt);
            }
        });
        Container.add(cpas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 260, -1));

        acc_name.setFont(new java.awt.Font("Bookman Old Style", 3, 20)); // NOI18N
        acc_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_name.setText("acc_fn");
        Container.add(acc_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 260, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "LOGOUT", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
           // Clear user session (if applicable)
           Object loggedInUser = null; 

        // Redirect to login form
        loginForm login = new loginForm();
        login.setVisible(true);

        // Close current dashboard
        this.dispose();
    }    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Session sess = Session.getInstance();
        if(sess.getUId()== 0){
             JOptionPane.showMessageDialog(null, "No account, Login First!");
             userDashboard usd = new userDashboard();
             usd.setVisible(true);
             this.dispose();      
        }else{
        acc_name.setText(""+sess.getUsername());   
        acc_email.setText(""+sess.getEmail());
        }
        
        iddisplay.setText("USER ID:"+sess.getUId());
        un.setText(""+sess.getUsername());
        email.setText(""+sess.getEmail());
        cn.setText(""+sess.getContact());
    }//GEN-LAST:event_formWindowActivated

    private void unActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void cpasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cpasMouseClicked
        changePass cp = new changePass();
        cp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cpasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accountDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accountDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel acc_email;
    private javax.swing.JLabel acc_name;
    private javax.swing.JTextField cn;
    private javax.swing.JLabel cpas;
    private javax.swing.JTextField email;
    private javax.swing.JLabel iddisplay;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField un;
    private javax.swing.JComboBox<String> ut;
    // End of variables declaration//GEN-END:variables
}
