/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import computershop.loginForm;
import config.dbConnector;
import config.passwordHasher;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Karystel
 */
public class createUserForm extends javax.swing.JFrame {

    /**
     * Creates new form adminDashboard
     */
    public createUserForm() {
        initComponents();
    }
    public static String em, user;
    
    public boolean duplicateCheck(){
        
        dbConnector dbc = new dbConnector();
        
        try{
        String query = "SELECT * FROM tbl_user  WHERE u_username = '" +username.getText()+ "' OR u_email = '" +email.getText()+ "'";
            ResultSet resultSet = dbc.getData(query);
            
            if(resultSet.next()){
                em = resultSet.getString("u_email");
                if(em.equals(email.getText())){
                    JOptionPane.showMessageDialog(null, "Email is Already Used!");
                    email.setText("");
                }
                user = resultSet.getString("u_username");
                if(user.equals(username.getText())){
                    JOptionPane.showMessageDialog(null, "Username is Already Used!");
                    username.setText("");
                }
                return true;
            }else{
                return false;
            }
        }catch(SQLException ex){
            System.out.println(""+ex);
            return false;
        }
        
    }
    public boolean updateCheck(){
        dbConnector dbc = new dbConnector();    
        try{
        String query = "SELECT * FROM tbl_user  WHERE (user_username = '" +username.getText()+ "' OR user_email = '" +email.getText()+ "') AND user_id != '"+uid.getText()+"'";
            ResultSet resultSet = dbc.getData(query);
            
            if(resultSet.next()){
                em = resultSet.getString("user_email");
                if(em.equals(email.getText())){
                    JOptionPane.showMessageDialog(null, "Email is Already Used!");
                    email.setText("");
                }
                user= resultSet.getString("user_username");
                if(user.equals(username.getText())){
                    JOptionPane.showMessageDialog(null, "Username is Already Used!");
                    username.setText("");
                }
                return true;
            }else{
                return false;
            }
        }catch(SQLException ex){
            System.out.println(""+ex);
            return false;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Container = new javax.swing.JPanel();
        refresh = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        add = new javax.swing.JButton();
        us = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ut = new javax.swing.JComboBox<>();
        password = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        confirmpass = new javax.swing.JPasswordField();
        showpass = new javax.swing.JCheckBox();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Container.setBackground(new java.awt.Color(255, 255, 255));
        Container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        refresh.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        refresh.setText("REFRESH");
        Container.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 130, 50));

        cancel.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        Container.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 140, 50));

        update.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        update.setText("UPDATE");
        update.setEnabled(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        Container.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 140, 50));

        delete.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        delete.setText("DELETE");
        Container.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 130, 50));

        clear.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        clear.setText("CLEAR");
        Container.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 130, 50));

        add.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        Container.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, 50));

        us.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        us.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Pending" }));
        Container.add(us, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 590, 210, 30));

        jLabel14.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel14.setText("USER STATUS:");
        Container.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 130, 70));

        uid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        uid.setEnabled(false);
        uid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uidActionPerformed(evt);
            }
        });
        Container.add(uid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 100, 30));

        jLabel11.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel11.setText("USER ID:");
        Container.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 100, 30));

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel7.setText("USERNAME:");
        Container.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 100, 30));

        username.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        Container.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 210, 30));

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel9.setText("EMAIL:");
        Container.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, 120, 50));

        email.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        Container.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 210, 30));

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel5.setText("USER TYPE:");
        Container.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 120, 70));

        cn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Container.add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, 210, 30));

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel10.setText("CONTACT:");
        Container.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 120, 70));

        ut.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "USER" }));
        Container.add(ut, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 210, 30));

        password.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Container.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 210, 30));

        jLabel12.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel12.setText("PASSWORD:");
        Container.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 120, 50));

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel8.setText("CONFIRM PASS:");
        Container.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 130, 50));

        confirmpass.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Container.add(confirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, 210, 30));

        showpass.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        showpass.setText("Show password");
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });
        Container.add(showpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 630, 130, 20));

        Header.setBackground(new java.awt.Color(51, 51, 0));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("CREATE USER FORM");
        Header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 410, -1));

        Container.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 110));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cream and Brown Retro Cafe Logo.png"))); // NOI18N
        Container.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 500, 500));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cream and Brown Retro Cafe Logo.png"))); // NOI18N
        Container.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 500, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed
        if(showpass.isSelected()){
            password.setEchoChar((char)0);
            confirmpass.setEchoChar((char)0);
        }
        else {
            password.setEchoChar('*');
            confirmpass.setEchoChar('*');
        }
    }//GEN-LAST:event_showpassActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void uidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uidActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        usersForm usf = new usersForm();
        usf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        if (username.getText().isEmpty() || email.getText().isEmpty() || cn.getText().isEmpty() || password.getText().isEmpty() || confirmpass.getText() .isEmpty()) {
           JOptionPane.showMessageDialog(null, "All fields are required!");
        } else if (password.getText().length() < 8) {
           JOptionPane.showMessageDialog(null, "Password must be at least 8 characters long.");
           password.setText(""); 
        } else if (!email.getText().endsWith("@gmail.com")) {
           JOptionPane.showMessageDialog(null, "Invalid email format..");
           email.setText("");
        } else if (!isValidContactNumber(cn.getText())) {
           JOptionPane.showMessageDialog(null, "Contact number must contain only digits and be 11 digits long.");
           cn.setText("");
        } else if (duplicateCheck()) {
           System.out.println("Duplicate Exist!"); 
        } else if (!password.getText().equals(confirmpass.getText())) {
           JOptionPane.showMessageDialog(null, "Passwords do not match.");
           password.setText("");
           confirmpass.setText("");    
        } else {
        dbConnector dbc = new dbConnector();
        try{
        String pass = passwordHasher.hashPassword(password.getText());
        if( dbc.insertData("INSERT INTO tbl_user (u_username, u_email, u_contact, u_usertype, u_password, u_status) "
                + "VALUES ('"+username.getText()+"','"+email.getText()+"', '"+cn.getText()+"','"+ut.getSelectedItem()+"','"+password.getText()+"','"+us.getSelectedItem()+"')")){   
        {
            
        }
            JOptionPane.showMessageDialog(null, "Registration Success!");
            loginForm lfr = new loginForm();
            lfr.setVisible(true);
            this.dispose();
            }else{
            JOptionPane.showMessageDialog(null, "Connection Error!");    
            }
        }catch(NoSuchAlgorithmException ex){
            System.out.println(""+ex);
        }
        } 
    }
    private boolean isValidContactNumber(String contact) {
    return contact.matches("\\d{11}");
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        if (username.getText().isEmpty() || email.getText().isEmpty() || cn.getText().isEmpty() || password.getText().isEmpty() || confirmpass.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "All fields are required!");
        } else if (password.getText().length() < 8) {
            JOptionPane.showMessageDialog(null, "Password must be at least 8 characters long.");
            password.setText("");
            confirmpass.setText("");
        } else if (!email.getText().endsWith("@gmail.com")) {
            JOptionPane.showMessageDialog(null, "Invalid email format..");
            email.setText("");
        } else if (!isValidContactNumber(cn.getText())) {
            JOptionPane.showMessageDialog(null, "Contact number must contain only digits and be 11 digits long.");
            cn.setText("");
        } else if (updateCheck()) {        
            System.out.println("Duplicate Exist!");
        } else if (!password.getText().equals(confirmpass.getText())) {
            JOptionPane.showMessageDialog(null, "Passwords do not match.");
            password.setText("");
            confirmpass.setText("");
        } else {
        dbConnector dbc = new dbConnector();
        dbc.updateData("UPDATE tbl_user SET u_username ='"+username.getText()+"',"
                + "u_email= '"+email.getText()+"',u_contact='"+cn.getText()+"',u_password='"+password.getText()+"',"
                        + "u_usertype='"+ut.getSelectedItem()+"',u_status = '"+us.getSelectedItem()+"' WHERE u_id = '"+uid.getText()+"'");
        
        
            usersForm usf = new usersForm();
            usf.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createUserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JPanel Header;
    public javax.swing.JButton add;
    private javax.swing.JButton cancel;
    private javax.swing.JButton clear;
    public javax.swing.JTextField cn;
    public javax.swing.JPasswordField confirmpass;
    private javax.swing.JButton delete;
    public javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPasswordField password;
    private javax.swing.JButton refresh;
    private javax.swing.JCheckBox showpass;
    public javax.swing.JTextField uid;
    public javax.swing.JButton update;
    public javax.swing.JComboBox<String> us;
    public javax.swing.JTextField username;
    public javax.swing.JComboBox<String> ut;
    // End of variables declaration//GEN-END:variables
}
