/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import computershop.loginForm;
import config.dbConnector;
import config.passwordHasher;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Karystel
 */
public class createUserForm extends javax.swing.JFrame {

    /**
     * Creates new form adminDashboard
     */
    public createUserForm() {
        initComponents();
    }
    public static String em, user;
    
    public boolean duplicateCheck(){
        
        dbConnector dbc = new dbConnector();
        
        try{
        String query = "SELECT * FROM tbl_user  WHERE u_username = '" +username.getText()+ "' OR u_email = '" +email.getText()+ "'";
            ResultSet resultSet = dbc.getData(query);
            
            if(resultSet.next()){
                em = resultSet.getString("u_email");
                if(em.equals(email.getText())){
                    JOptionPane.showMessageDialog(null, "Email is Already Used!");
                    email.setText("");
                }
                user = resultSet.getString("u_username");
                if(user.equals(username.getText())){
                    JOptionPane.showMessageDialog(null, "Username is Already Used!");
                    username.setText("");
                }
                return true;
            }else{
                return false;
            }
        }catch(SQLException ex){
            System.out.println(""+ex);
            return false;
        }
        
    }
    public boolean updateCheck(){
        dbConnector dbc = new dbConnector();    
        try{
        String query = "SELECT * FROM tbl_user  WHERE (u_username = '" +username.getText()+ "' OR u_email = '" +email.getText()+ "') AND u_id != '"+uid.getText()+"'";
            ResultSet resultSet = dbc.getData(query);
            
            if(resultSet.next()){
                em = resultSet.getString("u_email");
                if(em.equals(email.getText())){
                    JOptionPane.showMessageDialog(null, "Email is Already Used!");
                    email.setText("");
                }
                user= resultSet.getString("u_username");
                if(user.equals(username.getText())){
                    JOptionPane.showMessageDialog(null, "Username is Already Used!");
                    username.setText("");
                }
                return true;
            }else{
                return false;
            }
        }catch(SQLException ex){
            System.out.println(""+ex);
            return false;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Container = new javax.swing.JPanel();
        cpas = new javax.swing.JCheckBox();
        pw = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        refresh = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        add = new javax.swing.JButton();
        us = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        uid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ut = new javax.swing.JComboBox<>();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Container.setBackground(new java.awt.Color(255, 255, 255));
        Container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cpas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cpas.setText("Show password");
        cpas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpasActionPerformed(evt);
            }
        });
        Container.add(cpas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, -1, 20));

        pw.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Container.add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 562, 210, 30));

        jLabel15.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel15.setText("USER STATUS:");
        Container.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 130, 70));

        refresh.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        refresh.setText("REFRESH");
        Container.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 130, 50));

        cancel.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        cancel.setText("CANCEL");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        Container.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 140, 50));

        update.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        update.setText("UPDATE");
        update.setEnabled(false);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        Container.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 140, 50));

        delete.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        delete.setText("DELETE");
        Container.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 130, 50));

        clear.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        clear.setText("CLEAR");
        Container.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 130, 50));

        add.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        Container.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, 50));

        us.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        us.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Pending" }));
        Container.add(us, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 520, 210, 30));

        jLabel14.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel14.setText("PASSWORD:");
        Container.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, 130, 70));

        uid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        uid.setEnabled(false);
        uid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uidActionPerformed(evt);
            }
        });
        Container.add(uid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 100, 30));

        jLabel11.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel11.setText("USER ID:");
        Container.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 100, 30));

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel7.setText("USERNAME:");
        Container.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 100, 30));

        username.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        Container.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 210, 30));

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel9.setText("EMAIL:");
        Container.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 120, 50));

        email.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        Container.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 210, 30));

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel5.setText("USER TYPE:");
        Container.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 120, 70));

        cn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Container.add(cn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 210, 30));

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel10.setText("CONTACT:");
        Container.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, 120, 70));

        ut.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMIN", "USER" }));
        Container.add(ut, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 210, 30));

        Header.setBackground(new java.awt.Color(51, 51, 0));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("CREATE USER FORM");
        Header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 410, -1));

        Container.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 110));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cream and Brown Retro Cafe Logo.png"))); // NOI18N
        Container.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 500, 180));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cream and Brown Retro Cafe Logo.png"))); // NOI18N
        Container.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel16.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel16.setText("USER STATUS:");
        Container.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 130, 70));

        getContentPane().add(Container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void uidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uidActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        usersForm usf = new usersForm();
        usf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        if (username.getText().isEmpty() || email.getText().isEmpty() || cn.getText().isEmpty() || pw.getText().isEmpty()) {
           JOptionPane.showMessageDialog(null, "All fields are required!");
        } else if (pw.getText().length() < 8) {
            JOptionPane.showMessageDialog(null, "Password must be at least 8 characters long.");
            pw.setText("");
            cpas.setText("");
        } else if (!email.getText().endsWith("@gmail.com")) {
           JOptionPane.showMessageDialog(null, "Invalid email format..");
           email.setText("");
        } else if (!isValidContactNumber(cn.getText())) {
           JOptionPane.showMessageDialog(null, "Contact number must contain only digits and be 11 digits long.");
           cn.setText("");
        } else if (duplicateCheck()) {
           System.out.println("Duplicate Exist!"); 
        } else if (!pw.getText().equals(cpas.getText())) {
           JOptionPane.showMessageDialog(null, "Passwords do not match.");
           pw.setText("");
           cpas.setText("");   
        } else {
        dbConnector dbc = new dbConnector();
        if( dbc.insertData("INSERT INTO tbl_user (u_username, u_email, u_contact, u_usertype, u_password, u_status) "
                + "VALUES ('"+username.getText()+"','"+email.getText()+"', '"+cn.getText()+"','"+ut.getSelectedItem()+"', '"+pw.getText()+"','"+us.getSelectedItem()+"')")){
            {
                
            }
            JOptionPane.showMessageDialog(null, "Registration Success!");
            usersForm usf = new usersForm();
            usf.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Connection Error!");
        }
        } 
    }
    private boolean isValidContactNumber(String contact) {
    return contact.matches("\\d{11}");
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        if (username.getText().isEmpty() || email.getText().isEmpty() || cn.getText().isEmpty() || pw.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "All fields are required!");
        } else if (pw.getText().length() < 8) {
            JOptionPane.showMessageDialog(null, "Password must be at least 8 characters long.");
            pw.setText("");
            cpas.setText("");
        } else if (!email.getText().endsWith("@gmail.com")) {
            JOptionPane.showMessageDialog(null, "Invalid email format..");
            email.setText("");
        } else if (!isValidContactNumber(cn.getText())) {
            JOptionPane.showMessageDialog(null, "Contact number must contain only digits and be 11 digits long.");
            cn.setText("");
        } else if (updateCheck()) {        
            System.out.println("Duplicate Exist!");
        } else if (!pw.getText().equals(cpas.getText())) {
           JOptionPane.showMessageDialog(null, "Passwords do not match.");
           pw.setText("");
           cpas.setText("");   
        } else {
        dbConnector dbc = new dbConnector();
        dbc.updateData("UPDATE tbl_user SET u_username ='"+username.getText()+"',"
                + "u_email= '"+email.getText()+"',u_contact='"+cn.getText()+"',"
                        + "u_usertype='"+ut.getSelectedItem()+"',user_password='"+pw.getText()+"',u_status = '"+us.getSelectedItem()+"' WHERE u_id = '"+uid.getText()+"'");
        
        
            usersForm usf = new usersForm();
            usf.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_updateActionPerformed

    private void cpasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpasActionPerformed
        if(cpas.isSelected()){
            pw.setEchoChar((char)0);         
        }
        else {
            pw.setEchoChar('*');
            
        }
    }//GEN-LAST:event_cpasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(createUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(createUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(createUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(createUserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new createUserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JPanel Header;
    public javax.swing.JButton add;
    private javax.swing.JButton cancel;
    private javax.swing.JButton clear;
    public javax.swing.JTextField cn;
    private javax.swing.JCheckBox cpas;
    private javax.swing.JButton delete;
    public javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPasswordField pw;
    private javax.swing.JButton refresh;
    public javax.swing.JTextField uid;
    public javax.swing.JButton update;
    public javax.swing.JComboBox<String> us;
    public javax.swing.JTextField username;
    public javax.swing.JComboBox<String> ut;
    // End of variables declaration//GEN-END:variables
}
