/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computershop;

import config.dbConnector;
import config.passwordHasher;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Karystel
 */
public class forgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form forgotPassword
     */
    public forgotPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Container = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BACK = new javax.swing.JButton();
        sq = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        search = new javax.swing.JButton();
        ans = new javax.swing.JTextField();
        np = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Container.setBackground(new java.awt.Color(255, 255, 255));
        Container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Bookman Old Style", 3, 20)); // NOI18N
        jLabel15.setText("Answer:");
        Container.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 120, 30));

        jLabel14.setFont(new java.awt.Font("Bookman Old Style", 3, 20)); // NOI18N
        jLabel14.setText("Security Questions:");
        Container.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 220, 30));

        jLabel11.setFont(new java.awt.Font("Bookman Old Style", 3, 20)); // NOI18N
        jLabel11.setText("New Password:");
        Container.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 160, 50));

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 3, 20)); // NOI18N
        jLabel7.setText("Email:");
        Container.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 120, 40));

        BACK.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        BACK.setText("BACK");
        BACK.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 0)));
        BACK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACKActionPerformed(evt);
            }
        });
        Container.add(BACK, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 110, 60));

        sq.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        sq.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 0), 2));
        sq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqActionPerformed(evt);
            }
        });
        Container.add(sq, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 320, 50));

        save.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        save.setText("SAVE");
        save.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 0)));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        Container.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 470, 110, 60));

        search.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        search.setText("SEARCH");
        search.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(51, 51, 0)));
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        Container.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 110, 60));

        ans.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ans.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 0), 2));
        ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansActionPerformed(evt);
            }
        });
        Container.add(ans, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 320, 50));

        np.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        np.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 0), 2));
        np.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                npActionPerformed(evt);
            }
        });
        Container.add(np, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, 320, 50));

        email.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 0), 2));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        Container.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 320, 50));

        Header.setBackground(new java.awt.Color(51, 51, 0));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORGOT PASSWORD");
        Header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 940, -1));

        Container.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 110));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Container.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 109, -1, 390));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cream and Brown Retro Cafe Logo.png"))); // NOI18N
        Container.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 480, 500));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cream and Brown Retro Cafe Logo.png"))); // NOI18N
        jLabel3.setToolTipText("");
        Container.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 110, 480, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void sqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sqActionPerformed

    private void ansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ansActionPerformed

    private void npActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_npActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_npActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        String userEmail = email.getText();

        if (userEmail.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter your email.");
            return;
        }

        dbConnector dbc = new dbConnector();

        try {
            ResultSet rs = dbc.getData("SELECT * FROM tbl_user WHERE u_email = '" + userEmail + "'");
            if (rs.next()) {
                
                sq.setText(rs.getString("u_question"));
                sq.setEditable(false); 
            } else {
                JOptionPane.showMessageDialog(null, "Email not found.");
                sq.setText("");
            }
        } catch (Exception ex) {
            System.out.println("Error: " + ex.getMessage());
        
        }
    }//GEN-LAST:event_searchActionPerformed

    private void BACKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACKActionPerformed
        loginForm lf = new loginForm();
        lf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BACKActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        String userEmail = email.getText();
String answer = ans.getText();
String newPassword = np.getText();

if (userEmail.isEmpty() || sq.getText().isEmpty() || answer.isEmpty() || newPassword.isEmpty()) {
    JOptionPane.showMessageDialog(null, "All fields must be filled.");
    return;
}

if (newPassword.length() < 8) {
    JOptionPane.showMessageDialog(null, "Password must be at least 8 characters.");
    return;
}

dbConnector dbc = new dbConnector();

try {
    ResultSet rs = dbc.getData("SELECT * FROM tbl_user WHERE u_email = '" + userEmail + "'");
    if (rs.next()) {
        String correctAnswer = rs.getString("u_answer");
        String hashedInputAnswer = passwordHasher.hashPassword(answer);

        if (hashedInputAnswer.equals(correctAnswer)) {
            String hashedPassword = passwordHasher.hashPassword(newPassword);

            dbc.updateData("UPDATE tbl_user SET u_password = '" + hashedPassword + "' WHERE u_email = '" + userEmail + "'");

            email.setText("");
            sq.setText("");
            ans.setText("");
            np.setText("");

            loginForm lf = new loginForm();
            lf.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Incorrect security answer.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Please search for a valid email first.");
    }
} catch (Exception ex) {
    System.out.println("Error: " + ex.getMessage());
}

    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BACK;
    private javax.swing.JPanel Container;
    private javax.swing.JPanel Header;
    public javax.swing.JTextField ans;
    public javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextField np;
    public javax.swing.JButton save;
    public javax.swing.JButton search;
    public javax.swing.JTextField sq;
    // End of variables declaration//GEN-END:variables
}
