/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computershop;

import config.dbConnector;
import javax.swing.JOptionPane;

/**
 *
 * @author Karystel
 */
public class registrationForm extends javax.swing.JFrame {

    /**
     * Creates new form registrationForm
     */
    public registrationForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Container = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        confirmpass = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pcnumber = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        showpass = new javax.swing.JCheckBox();
        usertype = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cream and Brown Retro Cafe Logo.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Container.setBackground(new java.awt.Color(255, 255, 255));
        Container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(51, 51, 0));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("COMPUTER SHOP MANAGEMENT SYSTEM");
        Header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        Container.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 110));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Container.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 109, -1, 390));

        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 3, 20)); // NOI18N
        jLabel4.setText("REGISTRATION FORM");
        Container.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 240, 50));

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel5.setText("PC NUMBER:");
        Container.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 120, 70));

        username.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        Container.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 210, 30));

        jLabel7.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel7.setText("USERNAME:");
        Container.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 100, 30));

        jButton1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jButton1.setText("CANCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Container.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 500, 90, -1));

        jButton2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jButton2.setText("REGISTER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Container.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 500, 100, -1));

        confirmpass.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Container.add(confirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 210, 30));

        jLabel8.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel8.setText("CONFIRM PASS:");
        Container.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 130, 50));

        jLabel9.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel9.setText("EMAIL:");
        Container.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 120, 50));

        pcnumber.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pcnumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PC #", "PC 1", "PC 2", "PC 3", "PC 4", "PC 5", "PC 6", "PC 7", "PC 8", "PC 9", "PC 10", "PC 11", "PC 12", "PC 13", "PC 14", "PC 15", "PC 16", "PC 17", "PC 18", "PC 19", "PC 20", "PC 21", "PC 22", "PC 23", "PC 24", "PC 25", "PC 26", "PC 27", "PC 28", "PC 29", "PC 30", "PC 31", "PC 32", "PC 33", "PC 34", "PC 35", "PC 36", "PC 37", "PC 38", "PC 39", "PC 40", "PC 41", "PC 42", "PC 43", "PC 44", "PC 45", "PC 46", "PC 47", "PC 48", "PC 49", "PC 50", "PC 51", "PC 52", "PC 53", "PC 54", "PC 55", "PC 56", "PC 57", "PC 58", "PC 59", "PC 60", "PC 61", "PC 62", "PC 63", "PC 64", "PC 65", "PC 66", "PC 67", "PC 68", "PC 69", "PC 70", "PC 71", "PC 72", "PC 73", "PC 74", "PC 75", "PC 76", "PC 77", "PC 78", "PC 79", "PC 80", "PC 81", "PC 82", "PC 83", "PC 84", "PC 85", "PC 86", "PC 87", "PC 88", "PC 89", "PC 90", "PC 91", "PC 92", "PC 93", "PC 94", "PC 95", "PC 96", "PC 97", "PC 98", "PC 99", "PC 100" }));
        Container.add(pcnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 210, 30));

        jLabel10.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel10.setText("USERTYPE:");
        Container.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 120, 70));

        email.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        Container.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, 210, 30));

        password.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Container.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 210, 30));

        jLabel12.setFont(new java.awt.Font("Bookman Old Style", 3, 14)); // NOI18N
        jLabel12.setText("PASSWORD:");
        Container.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 120, 50));

        showpass.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        showpass.setText("Show password");
        showpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpassActionPerformed(evt);
            }
        });
        Container.add(showpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 470, 130, 20));

        usertype.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        usertype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT USER TYPE", "ADMIN", "USER" }));
        Container.add(usertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 210, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cream and Brown Retro Cafe Logo.png"))); // NOI18N
        Container.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 480, 500));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cream and Brown Retro Cafe Logo (2).png"))); // NOI18N
        Container.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 110, 480, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        loginForm lfm = new loginForm();
        lfm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

String em = email.getText().trim();
String user = username.getText().trim();
String pass = new String(password.getPassword()).trim();
String confirmPassword = new String(confirmpass.getPassword()).trim();
String pc = pcnumber.getSelectedItem().toString().trim();
String type = usertype.getSelectedItem().toString().trim();

if (pc.equals("PC #")) {
    JOptionPane.showMessageDialog(this, "Please select a valid PC number.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}
// Check if a valid user type is selected
if (type.equals("SELECT USER TYPE")) {
    JOptionPane.showMessageDialog(this, "Please select a valid user type.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// Validate username (at least 5 characters, only letters, numbers, and underscores)
if (!user.matches("[a-zA-Z0-9_]{5,}")) {
    JOptionPane.showMessageDialog(this, "Invalid Username! Must be at least 5 characters and contain only letters, numbers, and underscores.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// Validate inputs
if ( em.isEmpty() || user.isEmpty() || pass.isEmpty() || confirmPassword.isEmpty()) {
    JOptionPane.showMessageDialog(this, "All fields are required. Please fill out the form.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// Validate email format
String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
if (!em.matches(emailRegex)) {
    JOptionPane.showMessageDialog(this, "Invalid Email! Please enter a valid email.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// Validate password (at least 8 characters, 1 uppercase, 1 special character, 1 number)
if (!pass.matches("^(?=.*[A-Z])(?=.*[!@#$%^&*()_+\\-=\\[\\]{};'\"\\\\|,.<>\\/?])(?=.*\\d).{8,}$")) {
    JOptionPane.showMessageDialog(this, "Invalid Password! Must be at least 8 characters long, contain one uppercase letter, one special character, and one number.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// Validate Confirm Password (must match password)
if (!pass.equals(confirmPassword)) {
    JOptionPane.showMessageDialog(this, "Passwords do not match! Please enter the same password.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// Initialize database connection
dbConnector db = new dbConnector();

if (db == null) {
    JOptionPane.showMessageDialog(this, "Database connection failed.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// *Check if email already exists*
if (db.isEmailExists(em)) {
    JOptionPane.showMessageDialog(this, "Email already in use! Please use a different email.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}
if (db.isUsernameExists(user)) {
    JOptionPane.showMessageDialog(this, "Username already in use! Please use a different Username.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}
if (db.isPCExists(pc)) {
    JOptionPane.showMessageDialog(this, "PC number already in use! Please use a different PC.", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}




// Insert the user into the database
int inserted = db.insertUser( user, em, type, pc, pass);

if (inserted > 0) {
    JOptionPane.showMessageDialog(this, "Registration Successful! Your account is pending approval.", "Success", JOptionPane.INFORMATION_MESSAGE);
    loginForm login = new loginForm();
    login.setVisible(true);
    this.dispose();
} else {
    JOptionPane.showMessageDialog(this, "Registration failed. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
}

db.closeConnection(); // Close the database connection
    


       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void showpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpassActionPerformed
        if(showpass.isSelected()){
            password.setEchoChar((char)0);
            confirmpass.setEchoChar((char)0);
        }
        else {
            password.setEchoChar('*');
            confirmpass.setEchoChar('*');
        }
    }//GEN-LAST:event_showpassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JPanel Header;
    private javax.swing.JPasswordField confirmpass;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField password;
    private javax.swing.JComboBox<String> pcnumber;
    private javax.swing.JCheckBox showpass;
    private javax.swing.JTextField un;
    private javax.swing.JTextField un1;
    private javax.swing.JTextField un2;
    private javax.swing.JTextField un3;
    private javax.swing.JTextField un4;
    private javax.swing.JTextField un5;
    private javax.swing.JTextField un6;
    private javax.swing.JTextField username;
    private javax.swing.JComboBox<String> usertype;
    // End of variables declaration//GEN-END:variables
}
